name: Build and Publish to PyPI
on: push

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-20.04
    environment: release
    permissions:
      id-token: write
    steps:
    - name: Checkout py-osc2
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel

    - name: Build Release Distribution
      if: startsWith(github.ref, 'refs/tags') 
      run: |
        python3 setup.py sdist bdist_wheel

    - name: Build Snapshot Distribution
      if: ${{ !startsWith(github.ref, 'refs/tags') }}
      run: |
        python3 setup.py egg_info -b ".dev`date -u '+%Y%m%d%H%M%S'`" sdist bdist_wheel

    - name: Install and Run Tests
      run: |
        python3 -m pip install dist/*.whl
        python3 -m unittest tests/test*.py

    - name: Upload Distribution
      uses: actions/upload-artifact@v4
      with:
        name: Distribution
        path: dist/

    - name: Publish Release to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1

    - name: Publish Snapshot and Release to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
